### ISSUE TITLE
Unable to compile example from source

### ISSUE THREAD

**Issue by ghost** [mcourteaux/MultiTouch-Gestures-Java#2]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.657s
[INFO] Finished at: Fri Apr 22 14:09:41 CEST 2016
[INFO] Final Memory: 20M/1449M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project MultiTouchGesturesJava: Compilation failure: Compilation failure:
[ERROR] /Users/noman/Downloads/MultiTouch-Gestures-Java-master/src/main/java/com/martijncourteaux/multitouchgestures/MultiTouchGestureUtilities.java:[112,20] error: Entry is not public in HashMap; cannot be accessed from outside package
[ERROR] /Users/noman/Downloads/MultiTouch-Gestures-Java-master/src/main/java/com/martijncourteaux/multitouchgestures/MultiTouchGestureUtilities.java:[150,20] error: Entry is not public in HashMap; cannot be accessed from outside package
[ERROR] /Users/noman/Downloads/MultiTouch-Gestures-Java-master/src/main/java/com/martijncourteaux/multitouchgestures/MultiTouchGestureUtilities.java:[188,20] error: Entry is not public in HashMap; cannot be accessed from outside package
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by mcourteaux** [comment]
Well, that's unfortunate. Sorry about that. I should be fixed with the latest commit :)

**Comment by ghost** [comment]
No problem :) you just need to replace HashMap with Map. By the way any chance to make this for linux ?

**Comment by mcourteaux** [comment]
Personally, no, I won't be implementing this for Linux any time soon. So if you want to and can do it, go ahead. Just make a pull request :)
